class FontsHelper {
  static List<String> titleFonts = [
    "Abril Fatface",
    "Acme",
    "Alfa Slab One",
    "Amatic SC",
    "Anton",
    "Arvo",
    "Bangers",
    "Bebas Neue",
    "Cinzel",
    "Cormorant Garamond",
    "Dancing Script",
    "Domine",
    "Dosis",
    "EB Garamond",
    "Fjalla One",
    "Great Vibes",
    "Gravitas One",
    "Josefin Sans",
    "Kalam",
    "Karla",
    "Lobster",
    "Lora",
    "Lusitana",
    "Merriweather",
    "Monoton",
    "Montserrat",
    "Old Standard TT",
    "Open Sans",
    "Oswald",
    "Pacifico",
    "Pattaya",
    "Patua One",
    "Playfair Display",
    "Poiret One",
    "PT Serif",
    "Quicksand",
    "Raleway",
    "Righteous",
    "Roboto Slab",
    "Russo One",
    "Satisfy",
    "Sawarabi Mincho",
    "Slabo 27px",
    "Tangerine",
    "Ubuntu",
    "Vollkorn",
    "Yanone Kaffeesatz"
  ];
}
