name: sole_capsule
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sizer: ^2.0.15
  flutter_svg: ^2.0.9
  encrypt: ^5.0.3
  flutter_local_notifications: ^17.2.1+2
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  lottie: ^3.1.2
  shimmer: ^3.0.0
  video_player: ^2.8.6
  timeago: ^3.6.1
  flutter_blue_plus: ^1.32.7
  flutter_stripe: ^10.1.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  flutter_colorpicker: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  wifi_iot: ^0.3.19
  carousel_slider: ^5.0.0

  #state management
  provider: ^6.1.1

  # firebase packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.5
  firebase_app_check: ^0.2.1
  permission_handler: ^11.3.1
  remove_bg: ^0.0.3
  path_provider: ^2.1.3
  uuid: ^4.4.2
  vibration: ^1.9.0
  google_fonts: ^6.2.1
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  hive_generator: ^2.0.1
  build_runner: ^2.1.0


  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/sole.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/lottie/
    - assets/videos/
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/.env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
