# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Define the project settings
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Define the target
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Include Firebase dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'

  # # Post-install configuration
  # post_install do |installer|
  #   installer.pods_project.targets.each do |target|
  #     flutter_additional_ios_build_settings(target)
    # end
  # end
end
